version: '2'
services:
  web:
    build:
      context: docker/web/
    volumes:
      - './:/var/www/html'
    ports:
      - '8080:8000'
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
